FROM eclipse-temurin:21.0.8_9-jdk-alpine as builder
WORKDIR /app
COPY .mvn/ mvnw pom.xml ./
COPY .mvn .mvn
RUN ./mvnw dependency:resolve

COPY src ./src
#RUN apt update && apt install -y dos2unix
#RUN dos2unix mvnw
#RUN chmod +x mvnw
RUN ./mvnw package


FROM eclipse-temurin:21.0.8_9-jdk-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar employees.jar
CMD ["java", "-jar", "employees.jar"]
