name: Build
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
    build:
      runs-on: self-hosted
      steps:
          - name: Checkout
            uses: actions/checkout@v5

          - name: Setup Java
            uses: actions/setup-java@v5
            with:
              distribution: 'temurin' # See 'Supported distributions' for available options
              java-version: '21'
              cache: 'maven'

          - name: Build with Maven
            run: ./mvnw -B package