name: Build
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
    build:
      runs-on: self-hosted
      steps:
          - name: Hello
            run: echo "Hello github actions"