name: Build
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
    build:
      runs-on: self-hosted
      steps:
          - name: Checkout
            uses: actions/checkout@v5

          - name: Setup Java
            uses: actions/setup-java@v5
            with:
              distribution: 'temurin' # See 'Supported distributions' for available options
              java-version: '21'
              #cache: 'maven'

          - name: Build with Maven
            run: ./mvnw -B package

    integration-tests:
      runs-on: self-hosted
      needs: build
      steps:
        - name: kiírás
          run: echo "Integrációs tesztek"

    build-image:
      runs-on: self-hosted
      needs: build
      steps:
        - name: build image

    deploy:
      runs-on: self-hosted
      needs: build-image
      steps:
        - name: deploy