name: Build
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
    build:
      runs-on: self-hosted
      steps:
          - name: Checkout
            uses: actions/checkout@v5

          - name: Setup Java
            uses: actions/setup-java@v5
            with:
              distribution: 'temurin' # See 'Supported distributions' for available options
              java-version: '21'
              #cache: 'maven'

          - name: Build with Maven
            run: ./mvnw -B package
          - uses: actions/upload-artifact@v4
            with:
              name: employees.jar
              path: target/employees-*.jar

    integration-tests:
      if: false
      runs-on: self-hosted
      needs: build
      env:
        SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/employees
        SPRING_DATASOURCE_USERNAME: employees
        SPRING_DATASOURCE_PASSWORD: employees
      services:
        mariadb:
          image: mariadb:12.1.1-rc
          env:
            MARIADB_DATABASE: employees
            MARIADB_USER: employees
            MARIADB_PASSWORD: employees
            MARIADB_ROOT_PASSWORD: employees
          ports:
            - 3306:3306
          options: >-
            --health-cmd="healthcheck.sh --connect --innodb_initialized"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=3

      steps:
        - name: kiírás
          run: echo "Integrációs tesztek"
        - name: Checkout
          uses: actions/checkout@v5

        - name: Setup Java
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '21'
            #cache: 'maven'

        - name: Build with Maven
          run: ./mvnw -B verify

    build-image:
      runs-on: self-hosted
      needs: build
      permissions:
        contents: read
        packages: write
      steps:
        - name: build image
          run: echo "build image"
        - name: Checkout
          uses: actions/checkout@v5
        - uses: actions/download-artifact@v4
          with:
            name: employees.jar
            path: target/
        - name: Login github vontainer registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: DockerfileLayers
            push: true
            tags: ghcr.io/${{ github.repository }}:latest

    deploy:
      runs-on: self-hosted
      needs: build-image
      steps:
        - name: deploy
          run: echo "deploy"